### ISSUE TITLE
Af1.geneset() does not include AFUN identifiers 

### ISSUE THREAD

**Issue by sanjaynagi** [malariagen/malariagen-data-python#306]
The gff table from `Af1.geneset()` does not include AFUN identifiers anywhere, which most users will need to search for genes (and for me, prevents use for cDNA primers in AgamPrimer). 

If possible, it would be better to do this in the original google cloud/package data than some sort of post-load table merging, realistically anyone using the geneset is going to need AFUN gene/transcript identifiers. 

I don't quite know how these tables are initially generated, but ideally the ID column will contain AFUN identifiers, as in ag3.

**Comment by sanjaynagi** [comment]
@alimanfoo @jorels1 @leehart not knowing exactly how the google cloud storage works, is this a reasonable suggestion? (to edit the table and reupload to GCS) 

also i see now that `geneset()` has been deprecated in favour of `genome_features()`. 

happy to do this myself if I have access.

**Comment by alimanfoo** [comment]
Hi @sanjaynagi, the Af1.0 data release uses a new funestus assembly ("idAnoFuneDA-416_04" - catch name :smile:). I actually don't know where the GFF came from - @jorels1? 

This assembly does seem to be [on vectorbase](https://vectorbase.org/vectorbase/app/record/dataset/TMPTX_afunidAnoFuneDA416_04) now ([gff download](https://vectorbase.org/vectorbase/app/downloads/Current_Release/AfunestusidAnoFuneDA416_04/gff/data/)) but I don't think it has AFUN-like gene identifiers yet. Situation actually looks a bit messy as the version we've got in the release bucket is somewhat different from what vectorbase currently has.

**Comment by sanjaynagi** [comment]
cool, cc'ing alex @amakunin who I assume produced the assembly as well

**Comment by jorels1** [comment]
Apologies all for my late response. I had to study the situation properly to see where the problem was coming from. I prepared the annotation data most likely before the annotation data made its way to vectorbase and possibly where the AFUN identifiers were added. We downloaded the gff data from ncbi at: https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/62324/100/GCF_943734845.2_idAnoFuneDA-416_04/GCF_943734845.2_idAnoFuneDA-416_04_genomic.gff.gz. The notebook seen here (https://github.com/malariagen/vobs-funestus/blob/202_af_annotation_data/work/202_Af_annotation/annotation-gff_generation.ipynb) is what I used in making  a few edits to the GFF file: indicating the 2RL, 3RL and X chromosomes and removing all others.

**Comment by jorels1** [comment]
I think a way forward will be for me to download the vectorbase version of the gff file, prep it and then replace the current version in the release bucket. That way Sanjay can get on with his work. What do you think @alimanfoo and @amakunin?

**Comment by jorels1** [comment]
You are welcome Sanjay. I will let you know as soon as it is done.  @amakunin would definitely know whether such table exist and where to find it.

**Comment by amakunin** [comment]
Hi @sanjaynagi (cc @jorels1 @alimanfoo). Mapping of gene identifiers in AfunGA1 (LOC*) to AfunF3 (AFUN*) exists in vectorbase as othrology inference, e.g. https://vectorbase.org/vectorbase/app/record/gene/LOC125767311#category:taxonomy links to AFUN009971, so generating a table of, e.g., 1:1 orthologs is possible - I just don't know the system well enough to do it straight away and would appreciate any experience with that.

This situation happens because two funestus genomes exist in vectorbase separately:
- [AfunestusFUMOZ](https://vectorbase.org/vectorbase/app/record/dataset/TMPTX_afunFUMOZ) aka AfunF3 (http://dx.doi.org/10.1093/gigascience/giz063) is the primary genome for the species and it was annotated by VectorBase and thus has gene identifiers as AFUN*
- [idAnoFuneDA416_04](https://vectorbase.org/vectorbase/app/record/dataset/TMPTX_afunidAnoFuneDA416_04) aka AfunGA1 (http://dx.doi.org/10.12688/wellcomeopenres.18445.1, short name will appear in vectobase by mid-2023) is the secondary genome for the species and it was annotated by RefSeq and thus has gene identifiers as LOC*

**Comment by jorels1** [comment]
Hi @sanjaynagi, the updated gff3 file is now in the release bucket and it has the AFUN identifiers. Good luck.

**Comment by alimanfoo** [comment]
Hi @jorels1, just looking at the new GFF data, I can see this uses the same sequence identifiers "2RL", "3RL" and "X" as used in the reference genome and other data, so that is good. E.g., see [this notebook](https://colab.research.google.com/drive/12hTig_j6insjjhKu6lviy87bkFHgXPcQ?usp=sharing).

However, I think it would be helpful to tidy up the file naming a little to clarify where this GFF file came from and what you have done to it.

I.e., it looks like you have (1) downloaded [VectorBase-61_AfunestusidAnoFuneDA416_04.gff](https://vectorbase.org/common/downloads/Current_Release/AfunestusidAnoFuneDA416_04/gff/data/VectorBase-61_AfunestusidAnoFuneDA416_04.gff] and then (2) patched it to (i) rename the three main chromosomes and (ii) remove all records from unplaced contigs. 

Then you have (3) uploaded this file to GCS replacing the file at `gs://vo_afun_release/reference/genome/idAnoFuneDA-416_04/GCF_943734845.2_idAnoFuneDA-416_04_genomic.gff3.gz`.

Is that correct?

If so this is potentially confusing, because the file name "GCF_943734845.2_idAnoFuneDA-416_04_genomic.gff3.gz" on GCS suggests this file came from NCBI (as the original file did).

**Comment by alimanfoo** [comment]
Btw we also currently have an error when loading the GFF with default attributes:

![image](https://user-images.githubusercontent.com/703554/208932620-af621aa8-37b1-416d-bed4-8e244bbcc1f0.png)

**Comment by jorels1** [comment]
Hi @alimanfoo, thanks for pointing out the issue. I understand it is confusing and having thought about it I see why what I was trying to avoid was irrelevant. I will remake the file with the right name to reflect that it is the vectorbase version. Currently only their version has the AFUN identifiers. Secondly, I think in addition to adding the AFUN identifiers, their pipeline renamed the 'Name' key possibly to 'Note'. I am not sure it is as straightforward as just renaming Note to Name. What do you think?

**Comment by alimanfoo** [comment]
Thanks @jorels1. Can I suggest:

* Upload the new GFF file you have created by patching the vectorbase file to a new location at `gs://vo_afun_release/reference/genome/idAnoFuneDA-416_04/VectorBase-61_AfunestusidAnoFuneDA416_04_patched.gff.gz`
* Edit the config file at `gs://vo_afun_release/v1.0-config.json` to change the value of the `GENESET_GFF3_PATH` property to point to the new GFF path `reference/genome/idAnoFuneDA-416_04/VectorBase-61_AfunestusidAnoFuneDA416_04_patched.gff.gz`

Regarding the "Note" attribute, I don't think it would be quite right to rename in in the GFF to "Name", because it's not really a gene name but looks like it provides a standardised enzyme name. It looks sensible to include the "Note" field by default, but I'd leave it as it is in the GFF. Probably better would be to change the malariagen_data package to use different default fields. I could make a PR for that if you like.

**Comment by jorels1** [comment]
Thanks @alimanfoo. That sounds like a more robust solution. I will upload the vectobase gff3 file to another location and edit the 'v1.0-config.json' file to reflect the new file location and leave you to update the malariagen_data package.

**Comment by alimanfoo** [comment]
> Hi @alimanfoo, I have completed the two tasks outlined above.

Thanks @jorels1. Are you sure you updated the config file? I am still seeing this:

![image](https://user-images.githubusercontent.com/703554/208972456-42ad9bba-4efc-4def-b1bb-cec78febcace.png)

> I also think I will need to regenerate the data in 'vo_afun_release/reference/genome/idAnoFuneDA-416_04/Anopheles-funestus-DA-416_04_1_SEQANNOTATION.zarr' to reflect the updated gff3 file.

That may not be necessary if the NCBI and vectorbase GFF files are equivalent in that they contain the same gene, mRNA and CDS features (it doesn't matter what IDs they use).

**Comment by jorels1** [comment]
Hi @alimanfoo. Apologies, I am not sure what happened previously with the last file I edited. I have redone it now and the file reads like this:

![Screenshot 2022-12-22 at 09 24 00](https://user-images.githubusercontent.com/75442396/209102372-2c215f2b-f4da-4c16-ba96-c1c32abf63f2.png)


Okay, I will let the SEQANNOTATION files be.

Merry Christmas!

**Comment by jorels1** [comment]
Hi @sanjaynagi, Merry Christmas to you too!

I am not sure whether it is OK for working with agamprimer or not. Maybe test it and then we would see.

**Comment by sanjaynagi** [comment]
Yeah, Alex's post made me realise that in the case of AgamPrimer, it's fine to ask users to first find their funestus gene in VectorBase and look at orthologs to find the corresponding LOC identifier to input to AgamPrimer (which will become AnoPrimer!).

Thank you both, and Merry Christmas!!

**Comment by alimanfoo** [comment]
I've fixed the default attributes and released the fix in 7.1.2.
